name: Playwright Tests Workflow

on:
  workflow_dispatch:
    inputs:
      test_suites:
        description: 'Select test suites to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - TestCases_TaggedWithAbhinav
          - TestCases_TaggedWithJohn

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Determine test suites to run
        id: set-matrix
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.test_suites }}" != "all" ]; then
            echo "matrix={\"test-suite\":[{\"name\":\"${{ github.event.inputs.test_suites }}\",\"grep\":\"${{ env[format('{0}_{1}', 'GREP', github.event.inputs.test_suites)] }}\"}]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"test-suite\":[{\"name\":\"TestCases_TaggedWithAbhinav\",\"grep\":\"^(?=.*@abhinav)\"}]}" >> $GITHUB_OUTPUT
          fi

  run-tests:
    needs: setup-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        run: |
          echo "Running suite: ${{ matrix.test_suite.name }}"
          npx playwright test --grep "${{ matrix.test_suite.grep }}"