name: Playwright Tests Workflow 
on: push
jobs:
  testJobName:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 is to get the code 
        uses: actions/checkout@v3
      - name: Step 2 is to install dependencies
        run: npm install
      - name: Step 3 is to run the tests
        run: npx playwright install --with-deps
      - name: Step 4 is to run the tests
        run: npx playwright test first.spec.ts  